### ISSUE TITLE
Update date-time for iPad simulators based on iPad release dates

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/Nine41#7]
Ok, #4 got me curious about what the specific date should be for iPad.

After browsing through all the images on the various iPad and iPhone product pages, it turns out that Apple marketing materials appear to always use:

- `9:41` for iPhone status bar. And they **never** display the lock screen with a date. (We already knew this.)

- `9:41 AM` is also used for iPads, but their status bars now also display a date since iOS 13 (or 12?). This date is always **the release date of the device**.

So, what would be cool is to make our script choose the correct date for each iPad simulator. We can simplify by just using the latest devices, so we would only need dates for: `[iPad Pro, iPad Air, iPad, iPad Mini]`.

### Implementation notes

I think the only way to determine this precisely is from the simulator name + iOS version? If we can't determine the actual device, then we can fallback to one of: (1) the existing date we are using (first iPhone launch), (2) the date for the very first iPad, or (3) the date of the most recently release iPad. Not sure which is better.

A list of all devices and release dates:
https://en.wikipedia.org/wiki/List_of_iOS_devices

**Comment by saagarjha** [comment]
Hey, just stopping by with experience from [SimulatorStatusMagic](https://github.com/shinydevelopment/SimulatorStatusMagic), where we settled on Tuesday, January 9, 2007 as the "canonical date": https://github.com/shinydevelopment/SimulatorStatusMagic/pull/77. In short, the date shown isn't quite as simple as the release date of the device; when Marcom doesn't hide it behind something (which they do far to often for me to not suspect that this isn't coincidental) the date matches the date that the page is supposed to have been released. So that means the iPad will usually have a June date on developer.apple.com, a September date on the iOS pages, and a date matching their release date on the product pages (the apps on the App Store aren't a great example, IMO, because many of them were probably made by the engineering team and have obvious consistency issues). We went with the original iPhone's date as that is what QuickTime will put there, and it makes sense to match the date and time to the event anyways (plus, it's easier!). Just my 2¢.

**Comment by jessesquires** [comment]
Thanks for sharing @saagarjha !

I think you make a good point in shinydevelopment/SimulatorStatusMagic#77 -- noting that QuickTime uses `Tue Jan 9`. 

Perhaps it is better to always use this (currently that's what's happening for Nine41).

----

One of my original reasons for considering this change was because it felt weird to set the date to 2007 -- years before the iPad even existed. 😆 I realized the date is not shown in the status bar, but still.

----

I'll leave this issue open for a bit longer in case anyone else has thoughts.

But, right now, I'm leaning toward closing this as "won't fix".

**Comment by jessesquires** [comment]
Going to close.

We'll keep the date the same for all devices. (Current behavior.)
